### ISSUE TITLE
Display Brightness doesn't show up

### ISSUE THREAD

**Issue by PatrikOls** [JohnySeven/TWatchSK#87]
Display view doesn't show the "Display Brightness". Using a V3.0 Watch

**Comment by ba58smith** [comment]
Can you take a picture of what that screen looks like, and post it here, please?

**Comment by PatrikOls** [comment]
This is how the screen looks like. 
![image](https://user-images.githubusercontent.com/99754864/154224875-3b5bdb6e-2124-45a8-899c-59e6769407f3.png)

**Comment by ba58smith** [comment]
Ah, yes. Now that I see it, I remember - I removed that setting with https://github.com/JohnySeven/TWatchSK/pull/80. It was no longer useful, as you can read in the PR description.

**Comment by PatrikOls** [comment]
I can't get my watch to toggle any brightness. Don't know what brightness level I have, but it's to dark and I can't make it brighter.

https://user-images.githubusercontent.com/99754864/154278017-aa9f78ff-45a6-4808-b60d-fc4dd841464d.MOV

**Comment by JohnySeven** [comment]
You've metioned you have V3 watch, right? The code is tested and works fine on V1, let me see if there is something I can do.

**Comment by JohnySeven** [comment]
There are different Pins for running backlight on each version unfortunatelly. Will have to make V1-V3 firmwares, that would take few days and also TWatchSKDesigner will need to be updated to allow user to select correct version.

**Comment by PatrikOls** [comment]
Fantastic if that could be done! We are a long time cruisers and I love my SignalK server, extend it to a Twatch is something that will be very useful. Our yacht Sigrid af Skane at anchor.

![image](https://user-images.githubusercontent.com/99754864/154526361-22221783-2396-4366-9705-f9e479df0e4e.png)

**Comment by JohnySeven** [comment]
Nice, will hopefully have something this weekend done.

**Comment by PatrikOls** [comment]
Did a quick fix and changed the .h files in  .pio\libdeps\ttgo-t-watch\TTGO TWatch Library\src\board

Changed the:  TWATCH_TFT_BL              (gpio_num_t)12                                to 
                       TWATCH_TFT_BL              (gpio_num_t)12PIN 15 

Works on my V3 now.

**Comment by JohnySeven** [comment]
@PatrikOls I've finally managed to add support for V2 and even V3 - as I don't have hardware yet I can't test the Firmware on real device. May I ask you to download recent version of TWatchSK Designer for your OS: at https://github.com/JohnySeven/TWatchSKDesigner/releases/tag/v1.1 and test the current firmware uploaded via designer?

Note: during firmware upload please don't check "Clear device flash prior upload" as it would erase SPIFSS and your settings would get lost.

Thanks,
Jan

**Comment by JohnySeven** [comment]
@PatrikOls also PR #88 contains compilation support for V3 variant, feel free to try compiling the code and even respond to the PR with any issues or success!

**Comment by PatrikOls** [comment]
Have now tested using my TWatch V3and it works great! I used the TWatchSk Designer on Windows 11 with success.
Have also compiled and upload the firmware  using Windows 11 with success. 

Had to lower the upload speed to get the firmware to be uploaded when using Windows.


![image](https://user-images.githubusercontent.com/99754864/155893217-c64a7bbd-e0ed-4181-ab85-71c314ed82ff.png)

Many thanks!!!!

**Comment by JohnySeven** [comment]
Great, glad it works, please feel free to post any issues or new feature requests if you have one.

As it all works fine, I'm closing this one.

Thanks!
