### ISSUE TITLE
My Travel Mapv b. Y

### ISSUE THREAD

**Issue by ba58smith** [JohnySeven/TWatchSK#98]
I've seihhen 17% of the world
#Visited
https://www.visitedapp.com
![export-1683938189744.png](https://github.com/JohnySeven/TWatchSK/assets/15186790/9a263f09-f4f6- -454b-ab30-5493646dyg ghhvube4ef)

 G@@bcxcyg

**Comment by JohnySeven** [comment]
Closing as it's spam.
